"""initial schema

Revision ID: c0395f1a6a82
Revises: 
Create Date: 2026-07-10 18:55:46.415560
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0395f1a6a82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('team_leader_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_org_id'), 'teams', ['org_id'], unique=False)
    op.create_table('advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisors_team_id'), 'advisors', ['team_id'], unique=False)
    # teams.team_leader_id -> advisors.id is a circular FK; add it now that
    # advisors exists (a TL is themselves an advisor row).
    op.create_foreign_key(
        'fk_teams_team_leader', 'teams', 'advisors', ['team_leader_id'], ['id']
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('customer_ref', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_call_id', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('audio_uri', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('language_hint', sa.String(length=20), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('received', 'processing', 'done', 'failed', 'needs_review', name='callstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_calls_idempotency_key')
    )
    op.create_index('ix_calls_advisor_id', 'calls', ['advisor_id'], unique=False)
    op.create_index('ix_calls_called_at', 'calls', ['called_at'], unique=False)
    op.create_index('ix_calls_org_id', 'calls', ['org_id'], unique=False)
    op.create_table('call_scores',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('rubric_version', sa.String(length=20), nullable=False),
    sa.Column('compliance_capped', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Enum('no_needs_discovery', 'over_promising', 'pressure_tactics', 'price_before_value', 'undisclosed_costs', 'weak_trial_booking', 'talk_over_customer', 'pii_exposure', 'non_sales_call', name='flagtag', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warn', 'critical', name='flagseverity', native_enum=False, length=32), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=True),
    sa.Column('end_s', sa.Float(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('state', sa.Enum('open', 'disputed', 'upheld', 'dismissed', name='flagstate', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_flags_confidence'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flags_call_id', 'flags', ['call_id'], unique=False)
    op.create_index('ix_flags_state', 'flags', ['state'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('transcribe', 'diarise', 'redact', 'classify', 'analyse', 'validate', name='jobstage', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', 'dead', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'stage', name='uq_jobs_call_stage')
    )
    op.create_index('ix_jobs_call_id', 'processing_jobs', ['call_id'], unique=False)
    op.create_index('ix_jobs_claim', 'processing_jobs', ['status', 'run_after'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('rubric_version', sa.String(length=20), nullable=False),
    sa.Column('dimension', sa.Enum('needs_discovery', 'product_knowledge', 'objection_handling', 'compliance_integrity', 'next_step_booking', name='rubricdimension', native_enum=False, length=32), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('evidence_start_s', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('raw_score >= 0 AND raw_score <= 5', name='ck_scores_range'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scores_call_id', 'scores', ['call_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('code_switch_ratio', sa.Float(), nullable=True),
    sa.Column('wer_estimate', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_call_id'), 'transcripts', ['call_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('raised_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by'], ['advisors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disputes_flag_id', 'disputes', ['flag_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('advisor', 'customer', 'unknown', name='speakerrole', native_enum=False, length=32), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('redacted_text', sa.Text(), nullable=True),
    sa.CheckConstraint('end_s >= start_s', name='ck_segments_time_order'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segments_transcript_id', 'segments', ['transcript_id'], unique=False)
    op.create_table('calibration_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Enum('no_needs_discovery', 'over_promising', 'pressure_tactics', 'price_before_value', 'undisclosed_costs', 'weak_trial_booking', 'talk_over_customer', 'pii_exposure', 'non_sales_call', name='flagtag', native_enum=False, length=32), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Enum('true_positive', 'false_positive', name='calibrationverdict', native_enum=False, length=32), nullable=False),
    sa.Column('source_dispute_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_dispute_id'], ['disputes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_examples_tag'), 'calibration_examples', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the circular FK first so advisors/teams can be dropped.
    op.drop_constraint('fk_teams_team_leader', 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_calibration_examples_tag'), table_name='calibration_examples')
    op.drop_table('calibration_examples')
    op.drop_index('ix_segments_transcript_id', table_name='segments')
    op.drop_table('segments')
    op.drop_index('ix_disputes_flag_id', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_transcripts_call_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_scores_call_id', table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_jobs_claim', table_name='processing_jobs')
    op.drop_index('ix_jobs_call_id', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_flags_state', table_name='flags')
    op.drop_index('ix_flags_call_id', table_name='flags')
    op.drop_table('flags')
    op.drop_table('call_scores')
    op.drop_index('ix_calls_org_id', table_name='calls')
    op.drop_index('ix_calls_called_at', table_name='calls')
    op.drop_index('ix_calls_advisor_id', table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_advisors_team_id'), table_name='advisors')
    op.drop_table('advisors')
    op.drop_index(op.f('ix_teams_org_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('orgs')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
